//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActueelNS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActueelNS.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aan.
        /// </summary>
        public static string Aan {
            get {
                return ResourceManager.GetString("Aan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze applicatie maakt gebruik van de officiële NS api..
        /// </summary>
        public static string AboutApi {
            get {
                return ResourceManager.GetString("AboutApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string AboutEmailButton {
            get {
                return ResourceManager.GetString("AboutEmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb je tips, suggesties of vragen? Neem dan contact op met michiel@michielpost.nl.
        /// </summary>
        public static string AboutQuestions {
            get {
                return ResourceManager.GetString("AboutQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak je met veel plezier gebruik van Treintijden? Laat dan een review achter op de Marketplace..
        /// </summary>
        public static string AboutReview {
            get {
                return ResourceManager.GetString("AboutReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        public static string AboutReviewButton {
            get {
                return ResourceManager.GetString("AboutReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treintijden 2.3.7.
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actueel.
        /// </summary>
        public static string actueel {
            get {
                return ResourceManager.GetString("actueel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aan agenda toevoegen.
        /// </summary>
        public static string AddToCalendar {
            get {
                return ResourceManager.GetString("AddToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TREINTIJDEN.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steun Treintijden door een goede review achter te laten in de marketplace. Wil je nu een review plaatsen?.
        /// </summary>
        public static string AskReview {
            get {
                return ResourceManager.GetString("AskReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinding verbroken.
        /// </summary>
        public static string Caption_Disconnected {
            get {
                return ResourceManager.GetString("Caption_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik om te verzenden.
        /// </summary>
        public static string Caption_Send {
            get {
                return ResourceManager.GetString("Caption_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap om verbinding te maken.
        /// </summary>
        public static string Caption_TapToConnect {
            get {
                return ResourceManager.GetString("Caption_TapToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kon geen badges laden, probeer het later nog eens..
        /// </summary>
        public static string DonateError {
            get {
                return ResourceManager.GetString("DonateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treintijden is volledig gratis te gebruiken. Je kunt de ontwikkeling van de applicatie steunen door één of meerdere van onderstaande badges te kopen..
        /// </summary>
        public static string DonateIntro {
            get {
                return ResourceManager.GetString("DonateIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijs.
        /// </summary>
        public static string DonatePrice {
            get {
                return ResourceManager.GetString("DonatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steun deze app.
        /// </summary>
        public static string DonateTitle {
            get {
                return ResourceManager.GetString("DonateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favoriet.
        /// </summary>
        public static string favoriet {
            get {
                return ResourceManager.GetString("favoriet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herinner mij.
        /// </summary>
        public static string herinnermij {
            get {
                return ResourceManager.GetString("herinnermij", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to historie.
        /// </summary>
        public static string historie {
            get {
                return ResourceManager.GetString("historie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informatie.
        /// </summary>
        public static string informatie {
            get {
                return ResourceManager.GetString("informatie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instellingen.
        /// </summary>
        public static string instellingen {
            get {
                return ResourceManager.GetString("instellingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        public static string Ja {
            get {
                return ResourceManager.GetString("Ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie service is uitgeschakeld op deze telefoon..
        /// </summary>
        public static string LocatieServiceUitgeschakeld {
            get {
                return ResourceManager.GetString("LocatieServiceUitgeschakeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steun deze applicatie.
        /// </summary>
        public static string MainDonateButton {
            get {
                return ResourceManager.GetString("MainDonateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informatie.
        /// </summary>
        public static string MainInformatieButton {
            get {
                return ResourceManager.GetString("MainInformatieButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit is de lijst met jouw favoriete stations..
        /// </summary>
        public static string MainIntro1 {
            get {
                return ResourceManager.GetString("MainIntro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg meteen een station toe:.
        /// </summary>
        public static string MainIntro2 {
            get {
                return ResourceManager.GetString("MainIntro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to station toevoegen.
        /// </summary>
        public static string MainIntroButton {
            get {
                return ResourceManager.GetString("MainIntroButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatiebepaling....
        /// </summary>
        public static string MainLocationLoading {
            get {
                return ResourceManager.GetString("MainLocationLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herplannen.
        /// </summary>
        public static string MainPageHerplannen {
            get {
                return ResourceManager.GetString("MainPageHerplannen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent gepland.
        /// </summary>
        public static string MainPageRecent {
            get {
                return ResourceManager.GetString("MainPageRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beoordeel deze applicatie.
        /// </summary>
        public static string MainReviewButton {
            get {
                return ResourceManager.GetString("MainReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instellingen.
        /// </summary>
        public static string MainSettingsButton {
            get {
                return ResourceManager.GetString("MainSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storingen en werkzaamheden.
        /// </summary>
        public static string MainStoringenAppButton {
            get {
                return ResourceManager.GetString("MainStoringenAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectie verbroken..
        /// </summary>
        public static string Message_Disconnected {
            get {
                return ResourceManager.GetString("Message_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht op data....
        /// </summary>
        public static string NFCWaitPageText {
            get {
                return ResourceManager.GetString("NFCWaitPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC Connectie.
        /// </summary>
        public static string NFCWaitPageTitle {
            get {
                return ResourceManager.GetString("NFCWaitPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nooit.
        /// </summary>
        public static string Nooit {
            get {
                return ResourceManager.GetString("Nooit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan een reis.
        /// </summary>
        public static string planeenreis {
            get {
                return ResourceManager.GetString("planeenreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planner.
        /// </summary>
        public static string planner {
            get {
                return ResourceManager.GetString("planner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aankomst.
        /// </summary>
        public static string PlannerAankomst {
            get {
                return ResourceManager.GetString("PlannerAankomst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aankomst.
        /// </summary>
        public static string PlannerAankomstOption {
            get {
                return ResourceManager.GetString("PlannerAankomstOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NS- of OV-Jaarkaart.
        /// </summary>
        public static string PlannerCard {
            get {
                return ResourceManager.GetString("PlannerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mijn stations.
        /// </summary>
        public static string PlannerMijnStationsButton {
            get {
                return ResourceManager.GetString("PlannerMijnStationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan mijn reis.
        /// </summary>
        public static string PlannerSearchButton {
            get {
                return ResourceManager.GetString("PlannerSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon hogesnelheidstreinen.
        /// </summary>
        public static string PlannerToonHsl {
            get {
                return ResourceManager.GetString("PlannerToonHsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertrek.
        /// </summary>
        public static string PlannerVertrek {
            get {
                return ResourceManager.GetString("PlannerVertrek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertrek.
        /// </summary>
        public static string PlannerVertrekOption {
            get {
                return ResourceManager.GetString("PlannerVertrekOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via.
        /// </summary>
        public static string PlannerVia {
            get {
                return ResourceManager.GetString("PlannerVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prijs.
        /// </summary>
        public static string prijs {
            get {
                return ResourceManager.GetString("prijs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eerste klas.
        /// </summary>
        public static string PrijsEersteKlas {
            get {
                return ResourceManager.GetString("PrijsEersteKlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enkele reis.
        /// </summary>
        public static string PrijsEnkel {
            get {
                return ResourceManager.GetString("PrijsEnkel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er was een probleem met het ophalen van de prijzen. Mogelijk is er geen internet verbinding beschikbaar..
        /// </summary>
        public static string PrijsError {
            get {
                return ResourceManager.GetString("PrijsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen prijsinformatie beschikbaar voor deze reis..
        /// </summary>
        public static string PrijsGeenPrijs {
            get {
                return ResourceManager.GetString("PrijsGeenPrijs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijzen ophalen....
        /// </summary>
        public static string PrijsLoading {
            get {
                return ResourceManager.GetString("PrijsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retour.
        /// </summary>
        public static string PrijsRetour {
            get {
                return ResourceManager.GetString("PrijsRetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tweede klas.
        /// </summary>
        public static string PrijsTweedeKlas {
            get {
                return ResourceManager.GetString("PrijsTweedeKlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reisadvies.
        /// </summary>
        public static string reisadvies {
            get {
                return ResourceManager.GetString("reisadvies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aankomst.
        /// </summary>
        public static string ReisadviesAankomst {
            get {
                return ResourceManager.GetString("ReisadviesAankomst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verwijder zoekhistorie.
        /// </summary>
        public static string ReisadviesDeleteHistory {
            get {
                return ResourceManager.GetString("ReisadviesDeleteHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer eerst een zoekopdracht uit met de reisplanner..
        /// </summary>
        public static string ReisadviesDoZoek {
            get {
                return ResourceManager.GetString("ReisadviesDoZoek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eerder.
        /// </summary>
        public static string ReisadviesEerder {
            get {
                return ResourceManager.GetString("ReisadviesEerder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail....
        /// </summary>
        public static string ReisadviesEmailMenu {
            get {
                return ResourceManager.GetString("ReisadviesEmailMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er was een probleem met het ophalen van dit reisadvies. Mogelijk is er geen internet verbinding beschikbaar..
        /// </summary>
        public static string ReisadviesError {
            get {
                return ResourceManager.GetString("ReisadviesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string ReisadviesLater {
            get {
                return ResourceManager.GetString("ReisadviesLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mijn stations.
        /// </summary>
        public static string ReisadviesMijnStationsButton {
            get {
                return ResourceManager.GetString("ReisadviesMijnStationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geen zoekgeschiedenis.
        /// </summary>
        public static string ReisadviesNoHistory {
            get {
                return ResourceManager.GetString("ReisadviesNoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overstap.
        /// </summary>
        public static string ReisadviesOverstap {
            get {
                return ResourceManager.GetString("ReisadviesOverstap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reistijd.
        /// </summary>
        public static string ReisadviesReistijd {
            get {
                return ResourceManager.GetString("ReisadviesReistijd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herinner mij.
        /// </summary>
        public static string ReisadviesRemindMe {
            get {
                return ResourceManager.GetString("ReisadviesRemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herhaal zoekopdracht.
        /// </summary>
        public static string ReisadviesRepeatButton {
            get {
                return ResourceManager.GetString("ReisadviesRepeatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deel via NFC.
        /// </summary>
        public static string ReisadviesTapShareButton {
            get {
                return ResourceManager.GetString("ReisadviesTapShareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terugreis.
        /// </summary>
        public static string ReisadviesTerugreisButton {
            get {
                return ResourceManager.GetString("ReisadviesTerugreisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let op: latere vertrek/aankomsttijd.
        /// </summary>
        public static string ReisadviesVertraging {
            get {
                return ResourceManager.GetString("ReisadviesVertraging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let op: latere aankomsttijd.
        /// </summary>
        public static string ReisadviesVertragingAankomst {
            get {
                return ResourceManager.GetString("ReisadviesVertragingAankomst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to let op: latere vertrektijd.
        /// </summary>
        public static string ReisadviesVertragingVertrek {
            get {
                return ResourceManager.GetString("ReisadviesVertragingVertrek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertrek.
        /// </summary>
        public static string ReisadviesVertrek {
            get {
                return ResourceManager.GetString("ReisadviesVertrek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reisplanner.
        /// </summary>
        public static string reisplanner {
            get {
                return ResourceManager.GetString("reisplanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertrektijden laden....
        /// </summary>
        public static string ReisplannerLoading {
            get {
                return ResourceManager.GetString("ReisplannerLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw in 2.3.7
        ///- Direct plannen vanuit scherm met detail info treinrit
        ///
        ///Nieuw in 2.3.6
        ///- Tonen treinlengte bij ritinfo trein
        ///
        ///Nieuw in 2.3.5
        ///- Verbeteringen stations zoeken
        ///- Verbeteringen tiles
        ///
        ///Nieuw in 2.3.4
        ///- Station Barneveld Zuid
        ///
        ///Nieuw in 2.3.3
        ///- Verbeterde weergave uitvallende treinen
        ///- Station Nijmegen Goffert
        ///
        ///Nieuw in 2.3.2
        ///- Station Maastricht Noord
        ///- Deel een geplande reis via e-mail
        ///
        ///Nieuw in 2.3.1
        ///- Drukte-indicator legenda
        ///- Kleine verbeteringen en bugfixes
        ///
        ///Nieuw in [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De herinnering is succesvol toegevoegd..
        /// </summary>
        public static string ReminderAdded {
            get {
                return ResourceManager.GetString("ReminderAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treintijden.
        /// </summary>
        public static string ReminderAppTitle {
            get {
                return ResourceManager.GetString("ReminderAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toevoegen.
        /// </summary>
        public static string ReminderButton {
            get {
                return ResourceManager.GetString("ReminderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het is niet mogelijk een herinnering in het verleden toe te voegen..
        /// </summary>
        public static string ReminderError {
            get {
                return ResourceManager.GetString("ReminderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herinner mij voordat de trein vertrekt..
        /// </summary>
        public static string ReminderIntro {
            get {
                return ResourceManager.GetString("ReminderIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw trein naar {0} vertrekt om {1} op station {2} van spoor {3}..
        /// </summary>
        public static string ReminderServiceFormat {
            get {
                return ResourceManager.GetString("ReminderServiceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aankomende herinneringen.
        /// </summary>
        public static string ReminderUpcomming {
            get {
                return ResourceManager.GetString("ReminderUpcomming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to druk.
        /// </summary>
        public static string RitInfoDruk {
            get {
                return ResourceManager.GetString("RitInfoDruk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen ritinformatie beschikbaar..
        /// </summary>
        public static string RitInfoError {
            get {
                return ResourceManager.GetString("RitInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gemiddeld.
        /// </summary>
        public static string RitInfoGemiddeld {
            get {
                return ResourceManager.GetString("RitInfoGemiddeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treintijden laden....
        /// </summary>
        public static string RitInfoLoading {
            get {
                return ResourceManager.GetString("RitInfoLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rustig.
        /// </summary>
        public static string RitInfoRustig {
            get {
                return ResourceManager.GetString("RitInfoRustig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richting.
        /// </summary>
        public static string RitInfoViewModelRichting {
            get {
                return ResourceManager.GetString("RitInfoViewModelRichting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        public static string SettingsLanguageInput {
            get {
                return ResourceManager.GetString("SettingsLanguageInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie gegevens van de telefoon worden alleen gebruikt om automatisch stations bij u in de buurt te tonen. Dit kan uitgeschakeld worden in het instellingen menu..
        /// </summary>
        public static string SettingsPrivacy {
            get {
                return ResourceManager.GetString("SettingsPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations in de buurt tonen.
        /// </summary>
        public static string SettingsStationBuurt {
            get {
                return ResourceManager.GetString("SettingsStationBuurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storingen tonen op live tile.
        /// </summary>
        public static string SettingsStoringen {
            get {
                return ResourceManager.GetString("SettingsStoringen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie gebruiken.
        /// </summary>
        public static string SettingsUseLocation {
            get {
                return ResourceManager.GetString("SettingsUseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertrekstation invullen.
        /// </summary>
        public static string SettingsZoeken {
            get {
                return ResourceManager.GetString("SettingsZoeken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toon op de kaart.
        /// </summary>
        public static string showonmap {
            get {
                return ResourceManager.GetString("showonmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sluiten.
        /// </summary>
        public static string sluiten {
            get {
                return ResourceManager.GetString("sluiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stationkeuze.
        /// </summary>
        public static string stationkeuze {
            get {
                return ResourceManager.GetString("stationkeuze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stations.
        /// </summary>
        public static string stations {
            get {
                return ResourceManager.GetString("stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toevoegen aan favorieten.
        /// </summary>
        public static string StationTijdenAddButton {
            get {
                return ResourceManager.GetString("StationTijdenAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verwijder station.
        /// </summary>
        public static string StationTijdenDeleteButton {
            get {
                return ResourceManager.GetString("StationTijdenDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er was een probleem met het ophalen van de vertrektijden. Mogelijk is er geen internet verbinding beschikbaar..
        /// </summary>
        public static string StationTijdenError {
            get {
                return ResourceManager.GetString("StationTijdenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertrektijden laden....
        /// </summary>
        public static string StationTijdenLoading {
            get {
                return ResourceManager.GetString("StationTijdenLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toon op de kaart.
        /// </summary>
        public static string StationTijdenMapButton {
            get {
                return ResourceManager.GetString("StationTijdenMapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mijn stations.
        /// </summary>
        public static string StationTijdenMijnStationsButton {
            get {
                return ResourceManager.GetString("StationTijdenMijnStationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan een reis.
        /// </summary>
        public static string StationTijdenPlanReisButton {
            get {
                return ResourceManager.GetString("StationTijdenPlanReisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storingen.
        /// </summary>
        public static string storingen {
            get {
                return ResourceManager.GetString("storingen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er was een probleem met het ophalen van de storingen. Mogelijk is er geen internet verbinding beschikbaar..
        /// </summary>
        public static string StoringenError {
            get {
                return ResourceManager.GetString("StoringenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} storingen.
        /// </summary>
        public static string StoringenFormat {
            get {
                return ResourceManager.GetString("StoringenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geen storingen.
        /// </summary>
        public static string StoringenGeen {
            get {
                return ResourceManager.GetString("StoringenGeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op dit moment zijn er geen storingen bekend. Zodra er storingen zijn, zal Treintijden dit automatisch aangeven..
        /// </summary>
        public static string StoringenGeenLong {
            get {
                return ResourceManager.GetString("StoringenGeenLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storingen laden....
        /// </summary>
        public static string StoringenLoading {
            get {
                return ResourceManager.GetString("StoringenLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storingen.
        /// </summary>
        public static string StoringenStoringenHeader {
            get {
                return ResourceManager.GetString("StoringenStoringenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to werkzaamheden.
        /// </summary>
        public static string StoringenWerkzaamhedenHeader {
            get {
                return ResourceManager.GetString("StoringenWerkzaamhedenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} storing.
        /// </summary>
        public static string StoringFormat {
            get {
                return ResourceManager.GetString("StoringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toont het aantal storingen bij de vastgepinde tiles..
        /// </summary>
        public static string TaskHelperOmschrijving {
            get {
                return ResourceManager.GetString("TaskHelperOmschrijving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terugreis.
        /// </summary>
        public static string terugreis {
            get {
                return ResourceManager.GetString("terugreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treintijden.
        /// </summary>
        public static string TileAdviesControlTitle {
            get {
                return ResourceManager.GetString("TileAdviesControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trein.
        /// </summary>
        public static string TileAppTitle {
            get {
                return ResourceManager.GetString("TileAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reisplanner.
        /// </summary>
        public static string TileReisplanner {
            get {
                return ResourceManager.GetString("TileReisplanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storingen.
        /// </summary>
        public static string TileStoringen {
            get {
                return ResourceManager.GetString("TileStoringen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toevoegen.
        /// </summary>
        public static string toevoegen {
            get {
                return ResourceManager.GetString("toevoegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  treinstellen.
        /// </summary>
        public static string TrainCars {
            get {
                return ResourceManager.GetString("TrainCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uit.
        /// </summary>
        public static string Uit {
            get {
                return ResourceManager.GetString("Uit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vastpinnen.
        /// </summary>
        public static string vastpinnen {
            get {
                return ResourceManager.GetString("vastpinnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zorg dat Bluetooth aan staat..
        /// </summary>
        public static string VerifyBluetooth {
            get {
                return ResourceManager.GetString("VerifyBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertrektijden.
        /// </summary>
        public static string vertrektijden {
            get {
                return ResourceManager.GetString("vertrektijden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verwijder.
        /// </summary>
        public static string verwijder {
            get {
                return ResourceManager.GetString("verwijder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via station?.
        /// </summary>
        public static string ViaStation {
            get {
                return ResourceManager.GetString("ViaStation", resourceCulture);
            }
        }
    }
}
